---
title: "Analysis of Airbnb Price Determinants Using Linear Regression Modelt"
author: "Sharon"
date: "2023-12-01"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("tidyverse")
install.packages("latex2exp")
install.packages("gridExtra")
library(tidyverse) 
library(latex2exp)
library(gridExtra)
set.seed(302)
data=read_csv("AirBnB.cleansing_cleaned.csv")
attach(data)
trainrows <- sample(1:3870, 1935, replace=FALSE) 
train<- data[trainrows,]
test=data[-trainrows,]

```



```{r}
# take the summaries of the variables
summary(train[,c(6,19,20,21,22,24:31,34,35)])
summary(test[,c(6,19,20,21,22,24:31,34,35)])
```


```{r}
attach(train)
par(mfrow=c(3,3))
hist(price, breaks=20, main="price")
hist(`Age in years`, breaks=10, main="Age")
hist(accommodates, breaks=10, main="accommodates")
hist(bathrooms, breaks=10, main="bathrooms number")
hist(number_of_reviews, breaks=10, main="number of reviews")
hist(beds, breaks=10, main="beds number")
boxplot(guests_included, main = "guests_included")
boxplot(minimum_nights, main = "minimum_nights")
boxplot(`Total Rev`, main = "Total Review")


library(ggplot2)
a=ggplot(data=train, aes(x=bedrooms, y=price)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = 'Number 0f Bedrooms', y='Price', 
       title = 'Price VS Bedromms')
b=ggplot(data=train, aes(x=`Total Rev`, y=price)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = 'Total Review', y='Price', 
       title = 'Price VS Review')

grid.arrange(a,b, nrow=1)
```



```{r}
#Model 1

library(readr)
model_1=lm(price ~ property_type + room_type + Zipcode_mapped_values + accommodates + bathrooms + bedrooms + beds + review_scores_rating + host_response_time + minimum_nights, data = train)
summary(model_1)
```


```{r}
#Model 2
train=na.omit(train)
model_2=lm(price ~ room_type + Zipcode_mapped_values + accommodates + bathrooms + bedrooms, data = train)
summary(model_2)
```


```{r}
# F test
anova(model_2)
```



```{r}
#Partial F test
model_3=lm(price ~ room_type + Zipcode_mapped_values + accommodates, data = train)
anova(model_2,model_3)
```


```{r}
#model checking
r <- resid(model_2)
#check condition 1
plot(train$price ~ fitted(model_2), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(train$price ~ fitted(model_2)), lty=2)
#check condition 2
data1 = data.frame(train$price, train$accommodates , train$bathrooms , train$bedrooms)
pairs( data1 )

```





```{r}
plot(resid(model_2) ~ fitted(model_2), xlab="fitted", ylab="residuals", main="Residuals vs Fitted Values")
par(mfrow=c(3,5))
for(i in c(6,19,20,21,22,24:31,34,35)){
  plot(resid(model_2) ~ train[[i]], xlab=names(train[i]), ylab="residuals")
}
par(mfrow=c(2,2))
plot(model_2, which=c(1,2,3,4))

```


```{r}
#find outliers
which(rstandard(model_2) > 4 | rstandard(model_2) < -4)
```

```{r}
# determine whether there are leverage points
n <- nrow(train)
p <- length(coef(model_2))-1
# leverage cutoff
h_cut <- 2*(p+1)/n 
which(hatvalues(model_2) > h_cut)

```

```{r}
#cooks distance
D_cut <- qf(0.5, p+1, n-p-1)
which(cooks.distance(model_2) > D_cut)
```
```{r}
#dffits
fits_cut <- 2*sqrt((p+1)/n) 
which(abs(dffits(model_2)) > fits_cut)
```

```{r}
#dfbeta
beta_cut <- 2/sqrt(n) 
for(i in 1:6){
print(paste0("Beta ", i-1))
print(which(abs(dfbetas(model_2)[,i]) > beta_cut)) }
```



```{r}
install.packages("car")
library(MASS)
library(car) 
vif(model_2)
``` 

```{r}
#Model checking
test=na.omit(test)
model_4=lm(price ~ room_type + Zipcode_mapped_values + accommodates + bathrooms + bedrooms, data = test)
summary(model_4)
```

```{r}
#Partial F test
model_5=lm(price ~ room_type + Zipcode_mapped_values + accommodates, data = test)
anova(model_4,model_5)
```

```{r}
#condition 1
plot(test$price ~ fitted(model_2), main="Y versus Y-hat", xlab="Y-hat", ylab="Y")
abline(a = 0, b = 1)
lines(lowess(test$price ~ fitted(model_4)), lty=2)
#condition 2
data1 = data.frame(test$price, test$accommodates , test$bathrooms , test$bedrooms)
pairs( data1 )

```

```{r}
plot(resid(model_4) ~ fitted(model_4), xlab="fitted", ylab="residuals", main="Residuals vs Fitted Values")
par(mfrow=c(3,5))
for(i in c(6,19,20,21,22,24:31,34,35)){
  plot(resid(model_4) ~ test[[i]], xlab=names(test[i]), ylab="residuals")
}
par(mfrow=c(2,2))
plot(model_4, which=c(1,2,3,4))
```


```{r}
select = function(model, n)
{
  RSS <- sum(model$residuals^2)
  Rsquare <- summary(model)$r.squared
  Rsquare_adj <- summary(model)$adj.r.squared
  p <- length(model$coefficients) - 1
  AIC <- n*log(RSS/n) + 2*p
  AICc <- AIC + (2*(p+2)*(p+3)/(n-p-1))
  BIC <- n*log(RSS/n) + (p+2)*log(n) 
  num <- c(RSS, Rsquare, Rsquare_adj, AIC, AICc, BIC)
  names(num) <- c("RSS", "Rsquare", "Rsquare_adj", "AIC", "AIC_c", "BIC")
  return(num)
}

s1 <- select(model_1, nrow(train))
s1
s2 <- select(model_2, nrow(train))
s2
s3 <- select(model_4, nrow(test))
s3
```





